[package]
name = "helloword"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk= "1.1"
ini = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


